// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QQEgg_Backend.Models
{
    public partial class TAorders
    {
        public int AorderId { get; set; }
        public int? SupplierId { get; set; }
        public int? AdvertiseId { get; set; }
        public DateTime OrderDate { get; set; }
        public DateTime? EndDate { get; set; }
        public int? Clicks { get; set; }
        public decimal? Price { get; set; }

        public virtual TAdvertise Advertise { get; set; }
        public virtual TSuppliers Supplier { get; set; }
    }
}