// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QQEgg_Backend.Models
{
    public partial class TCorders
    {
        public TCorders()
        {
            TCorderDetail = new HashSet<TCorderDetail>();
        }

        public int OrderId { get; set; }
        public int? CustomerId { get; set; }
        public int? ProductId { get; set; }
        public DateTime OrderDate { get; set; }
        public DateTime? ReturnDate { get; set; }
        public DateTime? CancelDate { get; set; }
        public DateTime? TakeDate { get; set; }
        public DateTime? EndDate { get; set; }

        public virtual TCustomers Customer { get; set; }
        public virtual TProducts Product { get; set; }
        public virtual ICollection<TCorderDetail> TCorderDetail { get; set; }
    }
}