// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QQEgg_Backend.Models
{
    public partial class TCoupons
    {
        public TCoupons()
        {
            TCorderDetail = new HashSet<TCorderDetail>();
        }

        public int CouponId { get; set; }
        public string Code { get; set; }
        public decimal? Discount { get; set; }
        public DateTime? ExpiryDate { get; set; }
        public int? Quantity { get; set; }
        public bool? Available { get; set; }

        public virtual ICollection<TCorderDetail> TCorderDetail { get; set; }
    }
}