// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QQEgg_Backend.Models
{
    public partial class TEvaluations
    {
        public int EvaluationId { get; set; }
        public int? CustomerId { get; set; }
        public int? RoomId { get; set; }
        public int? TitleId { get; set; }
        public DateTime? Date { get; set; }
        public string Description { get; set; }
        public string Response { get; set; }
        public int? Star { get; set; }

        public virtual TCustomers Customer { get; set; }
        public virtual TPsiteRoom Room { get; set; }
        public virtual TEtitle Title { get; set; }
    }
}