// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QQEgg_Backend.Models
{
    public partial class TProducts
    {
        public TProducts()
        {
            TCorders = new HashSet<TCorders>();
            TPsite = new HashSet<TPsite>();
        }

        public int ProductId { get; set; }
        public int? SupplierId { get; set; }
        public string Name { get; set; }

        public virtual TSuppliers Supplier { get; set; }
        public virtual ICollection<TCorders> TCorders { get; set; }
        public virtual ICollection<TPsite> TPsite { get; set; }
    }
}