// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QQEgg_Backend.Models
{
    public partial class TPsite
    {
        public TPsite()
        {
            TPsiteRoom = new HashSet<TPsiteRoom>();
        }

        public int SiteId { get; set; }
        public int? ProductId { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string OpenTime { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }

        public virtual TProducts Product { get; set; }
        public virtual ICollection<TPsiteRoom> TPsiteRoom { get; set; }
    }
}