// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QQEgg_Backend.Models
{
    public partial class TSuppliers
    {
        public TSuppliers()
        {
            TAorders = new HashSet<TAorders>();
            TProducts = new HashSet<TProducts>();
        }

        public int SupplierId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
        public int? CreditPoints { get; set; }
        public bool? BlackListed { get; set; }

        public virtual ICollection<TAorders> TAorders { get; set; }
        public virtual ICollection<TProducts> TProducts { get; set; }
    }
}